### ISSUE TITLE
Undefined method `merge_into` after upgrading to 1.0.2

### ISSUE THREAD

**Issue by pokonski** [anycable/anycable-rails#139]
### Tell us about your environment

**Ruby version: 2.6.5**
**`anycable` gem version: 1.0.1**
**`rails` gem version: 5.2.4.2**
**`grpc` gem version:  grpc-1.31.1-x86_64-linux**

### What did you do?

Upgraded anycable-rails from 0.6.5 to 1.0.2 and anycable from 0.6.5 to 1.0.1

### What did you expect to happen?

For everything to keep working.

### What actually happened?

Attempts to connect from AnyCable-Go server to the gRPC server result in the following error:

```
RPC Connect: <AnyCable::ConnectionRequest: env: <AnyCable::Env: url: "http://localhost:3334/cable?access_token=snip", headers: {"REMOTE_ADDR"=>"127.0.0.1"}, cstate: {}, istate: {}>>
undefined method `merge_into' for #<ActionDispatch::MiddlewareStack:0x000055e67c594d00>:
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/rack.rb:49:in `block in app'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/rack.rb:46:in `synchronize'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/rack.rb:46:in `app'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:196:in `build_rack_request'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:138:in `request'
/home/piotrek/my_app/app/channels/application_cable/connection.rb:5:in `connect'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:82:in `handle_open'
/home/piotrek/.gem/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:20:in `connect'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
/home/piotrek/.gem/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
/home/piotrek/.gem/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/piotrek/.gem/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:72:in `block in wrap'
/home/piotrek/.gem/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/home/piotrek/.gem/gems/activesupport-6.0.3.2/lib/active_support/reloader.rb:71:in `wrap'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/middlewares/executor.rb:16:in `call'
/home/piotrek/.gem/gems/anycable-1.0.1/lib/anycable/middleware.rb:13:in `request_response'
```

The relevant code for my Connection class, minimized to leave just the failing part:

```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base

    def connect
      request # This is where the failure occurs
    end
  end
end
```

**Comment by palkan** [comment]
Interesting.
The `merge_into` method is called on AnyCable::Rails::Rack.middleware, which is define here: https://github.com/anycable/anycable-rails/blob/76b4382045b0de25a55f2ac58efa8f1106673e80/lib/anycable/rails/rack.rb#L33-L35

And it should be an instance of `Rails::Configuration::MiddlewareStackProxy`, not `ActionDispatch::MiddlewareStack` (as we can see from the stack trace).

Do you have any middleware customizations in your app?

**Comment by pokonski** [comment]
Indeed I do:

```
    config.middleware.insert_before 0, Rack::Cors do
        # cors settings here
      end
    end
    config.middleware.insert_after Rack::Cors, BasicAuth
    config.middleware.insert_after BasicAuth, Warden::Manager do |manager|
      # settings here
    end

    config.middleware.use Rack::Deflater```

**Comment by palkan** [comment]
> And it should be an instance of Rails::Configuration::MiddlewareStackProxy, not ActionDispatch::MiddlewareStack 

I found that we override `@middleware` while building a rack app: https://github.com/anycable/anycable-rails/blob/76b4382045b0de25a55f2ac58efa8f1106673e80/lib/anycable/rails/rack.rb#L46-L52

That should be called once but looks like in your case it's called at least twice.

My suggestion is that the following line fails (causing our memoization not to work as expected): https://github.com/anycable/anycable-rails/blob/76b4382045b0de25a55f2ac58efa8f1106673e80/lib/anycable/rails/rack.rb#L50

Could you check logs for other exceptions?

Also, could you please try the latest master? I pushed a commit fixes the confusing `@middleware` override, I think, now we should see a different exception.

**Comment by pokonski** [comment]
I found another exception that happened right before the original one:

```
undefined method `new' for nil:NilClass:
/home/piotrek/.gem/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:37:in `build'
/home/piotrek/.gem/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
/home/piotrek/.gem/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:101:in `each'
/home/piotrek/.gem/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:101:in `inject'
/home/piotrek/.gem/gems/actionpack-5.2.4.2/lib/action_dispatch/middleware/stack.rb:101:in `build'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/rack.rb:50:in `block in app'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/rack.rb:46:in `synchronize'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/rack.rb:46:in `app'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:196:in `build_rack_request'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:138:in `request'
/home/piotrek/my_app/app/channels/application_cable/connection.rb:15:in `find_profile'
/home/piotrek/my_app/app/channels/application_cable/connection.rb:8:in `connect'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/actioncable/connection.rb:82:in `handle_open'
/home/piotrek/.gem/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:20:in `connect'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
/home/piotrek/.gem/gems/grpc-1.31.1-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
/home/piotrek/.gem/gems/anycable-1.0.1/lib/anycable/middleware.rb:14:in `block in request_response'
/home/piotrek/.gem/gems/anycable-rails-1.0.2/lib/anycable/rails/middlewares/executor.rb:16:in `block in call'
deadline is 1970-01-01 00:59:59 +0100; (now=2020-09-09 14:35:08 +0200)```

Will check master and report :)

**Comment by pokonski** [comment]
After upgrading to the master version I no longer receive the `merge_into` exception, but only this:


```
undefined method `new' for nil:NilClass:
/home/piotrek/.gem/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:37:in `build'
/home/piotrek/.gem/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:101:in `block in build'
/home/piotrek/.gem/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:101:in `each'
/home/piotrek/.gem/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:101:in `inject'
/home/piotrek/.gem/gems/actionpack-5.2.4.3/lib/action_dispatch/middleware/stack.rb:101:in `build'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/rack.rb:50:in `block (2 levels) in app'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/rack.rb:49:in `yield_self'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/rack.rb:49:in `block in app'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/rack.rb:46:in `synchronize'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/rack.rb:46:in `app'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/actioncable/connection.rb:196:in `build_rack_request'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/actioncable/connection.rb:138:in `request'
/home/piotrek/my_app/app/channels/application_cable/connection.rb:15:in `find_profile'
/home/piotrek/my_app/app/channels/application_cable/connection.rb:8:in `connect'
/home/piotrek/.gem/bundler/gems/anycable-rails-4276e0061e02/lib/anycable/rails/actioncable/connection.rb:82:in `handle_open'
/home/piotrek/.gem/gems/anycable-1.0.1/lib/anycable/rpc_handler.rb:20:in `connect'
/home/piotrek/.gem/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `call'
/home/piotrek/.gem/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/rpc_desc.rb:60:in `block in handle_request_response'
/home/piotrek/.gem/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:178:in `block (2 levels) in intercept!'
/home/piotrek/.gem/gems/grpc-1.32.0-x86_64-linux/src/ruby/lib/grpc/generic/interceptors.rb:181:in `block in intercept!'
```

**Comment by palkan** [comment]
Could you share the values for `Rails.application.config.session_store` and `AnyCable::Rails::Rack.default_middleware_stack.middlewares`?

**Comment by pokonski** [comment]
```
[1] pry(main)> Rails.application.config.session_store
=> nil
[2] pry(main)> AnyCable::Rails::Rack.default_middleware_stack.middlewares
=> [NilClass]
```

(It's an API so no session middleware is disabled with `Rails.application.config.session_store :disabled` in an initializer)

**Comment by palkan** [comment]
> I'll try to prepare a minimal repro project.

No need. We have enough information to fix it. Thank you!

Could you please try the latest master? I just pushed a fix.

**Comment by pokonski** [comment]
@palkan Awesome! I can confirm connections and everything else now work correctly :grin: Thank you for the help and the fix :bow:

**Comment by palkan** [comment]
Great! Released in 1.0.3
