### ISSUE TITLE
Cannot install on Rails 7.1 - Google::Protobuf error

### ISSUE THREAD

**Issue by noctivityinc** [anycable/anycable-rails#202]
### Tell us about your environment

ruby "3.3.4"
gem "rails", "~> 7.1.3", ">= 7.1.3.4"
gem "anycable-rails", "~> 1.4"

### What did you do?

All I did was install anycable-rails and then tried to run setup.

### What did you expect to happen?

It would work and not crash my app

### What actually happened?
```
11:30 AM ~/Projects/wecora/seven (ac2) => rails g anycable:setup
/Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/anycable-core-1.4.3/lib/anycable/protos/rpc_pb.rb:8:in `<main>': undefined method `build' for an instance of Google::Protobuf::DescriptorPool (NoMethodError)

Google::Protobuf::DescriptorPool.generated_pool.build do
                                               ^^^^^^
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/anycable-core-1.4.3/lib/anycable/rpc.rb:3:in `<main>'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/anycable-core-1.4.3/lib/anycable.rb:16:in `<main>'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/anycable-rails-core-1.4.4/lib/anycable/rails.rb:3:in `<main>'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/anycable-rails-core-1.4.4/lib/anycable-rails.rb:3:in `<main>'
        from <internal:/Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from <internal:/Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/site_ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/zeitwerk-2.6.17/lib/zeitwerk/kernel.rb:34:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bundler-2.5.11/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bundler-2.5.11/lib/bundler/runtime.rb:55:in `each'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bundler-2.5.11/lib/bundler/runtime.rb:55:in `block in require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bundler-2.5.11/lib/bundler/runtime.rb:44:in `each'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bundler-2.5.11/lib/bundler/runtime.rb:44:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bundler-2.5.11/lib/bundler.rb:207:in `require'
        from /Users/jlippiner/Projects/wecora/seven/config/application.rb:7:in `<main>'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command/actions.rb:15:in `require_application!'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command/actions.rb:19:in `boot_application!'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/commands/generate/generate_command.rb:21:in `perform'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/thor-1.3.1/lib/thor/command.rb:28:in `run'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/thor-1.3.1/lib/thor/invocation.rb:127:in `invoke_command'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command/base.rb:178:in `invoke_command'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/thor-1.3.1/lib/thor.rb:527:in `dispatch'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command/base.rb:73:in `perform'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command.rb:71:in `block in invoke'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command.rb:149:in `with_argv'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/command.rb:69:in `invoke'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/railties-7.1.3.4/lib/rails/commands.rb:18:in `<main>'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
        from /Users/jlippiner/.rvm/rubies/ruby-3.3.4/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
        from /Users/jlippiner/.rvm/gems/ruby-3.3.4@wecora-7/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
        from bin/rails:4:in `<main>'
```

**Comment by palkan** [comment]
Looks like you've upgraded the `google-protobuf` gem; v4 is currently not supported; adding `gem "google-protobuf", "~> 3.25"` should fix the issue.

Or upgrade `anycable-core` (and `anycable`) to 1.4.4 (the protobuf version requirement has been fixed there).

**Comment by noctivityinc** [comment]
Can I use any cable-core with rails?  The docs say to use anycable-rails
or something like that, though I cant even find that repo anymore.  Where
can I find the latest docs for this for Rails 7?

**Comment by palkan** [comment]
anycable-rails depends on anycable-core

In your case, running `bundle update anycable` (or `bundle update anycable-core`) should do the trick; no need to add it explicitly to the Gemfile

**Comment by noctivityinc** [comment]
@palkan Ok that worked with 1.5.1 but now I get this:

`anycable | ⛔️ WARNING: AnyCable RPC pool size (30) is greater than DB pool size (5)`

Without any information about which database or HOW to adjust the pool sizes for either AC or the DB.  Any docs here?

**Comment by palkan** [comment]
> Without any information about which database or HOW to adjust the pool sizes for either AC or the DB.

This message says that your Active Record pool size is 5 (the default), which is less than the AnyCable gRPC worker pool size (also the default, 30). To avoid competition for DB connections, it's better to keep the in sync.

> Any docs here?

https://docs.anycable.io/edge/ruby/configuration?id=concurrency-settings

**Comment by maximbond** [comment]
Does anyone has the same issue on 1.6.0?

**Tell us about your environment**
ruby (3.2.6)
anycable (1.6.0)
anycable-core (1.6.0)
anycable-rails (1.6.0)
anycable-rails-core (1.6.0)
google-protobuf (4.30.2-x86_64-linux)
grpc (1.71.0-x86_64-linux)

**What did you do?**
I upgraded anycable gems from 1.5.1 to 1.6.0 and run tests.

**What did you expect to happen?**
That tests and the app would work.

**What actually happened?**
```
+ CI=true bundler exec rails db:create db:schema:load --trace
[bin/rails](https://bitbucket.org/rightwayhealthcare/backend/src/7da1ff83cbec96ee0b9983c785d9831379a18424/bin/rails) aborted!
NoMethodError: undefined method `build' for #<Google::Protobuf::DescriptorPool:0x00007f1e663bda68> (NoMethodError)
Google::Protobuf::DescriptorPool.generated_pool.build do
                                               ^^^^^^
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rightway-grpc-25.1.1/dist/ruby/rightway/common/health/check/request/health_check_request_pb.rb:6:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rightway-grpc-25.1.1/dist/ruby/rightway/common/health/health_pb.rb:6:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rightway-grpc-25.1.1/dist/ruby/rightway/common/health/health_services_pb.rb:5:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rightway-grpc-25.1.1/dist/ruby/common-rpc.rb:3:in `<top (required)>'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rightway-grpc-25.1.1/dist/ruby/rightway-grpc.rb:3:in `require_relative'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rightway-grpc-25.1.1/dist/ruby/rightway-grpc.rb:3:in `<top (required)>'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:55:in `each'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:55:in `block in require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:44:in `each'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.17/lib/bundler/runtime.rb:44:in `require'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/bundler-2.4.17/lib/bundler.rb:187:in `require'
/opt/atlassian/pipelines/agent/build/config/application.rb:23:in `<top (required)>'
/opt/atlassian/pipelines/agent/build/Rakefile:4:in `require_relative'
/opt/atlassian/pipelines/agent/build/Rakefile:4:in `<top (required)>'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/rake_module.rb:29:in `load_rakefile'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:740:in `raw_load_rakefile'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:126:in `block in load_rakefile'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:214:in `standard_exception_handling'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/application.rb:125:in `load_rakefile'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/rake-13.2.1/lib/rake/rake_module.rb:59:in `with_application'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/command.rb:156:in `invoke_rake'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/command.rb:73:in `block in invoke'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/command.rb:149:in `with_argv'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/command.rb:69:in `invoke'
/opt/atlassian/pipelines/agent/build/vendor/bundle/ruby/3.2.0/gems/railties-7.1.5.1/lib/rails/commands.rb:18:in `<top (required)>'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
<internal:/usr/local/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:38:in `require'
bin/rails:4:in `<main>'

**Comment by palkan** [comment]
> rightway-grpc-25.1.1/dist/ruby/rightway/common/health/check/request/health_check_request_pb.rb

Looks like `rightway-grpc` uses an older protobuf DSL but has not upper bound for the protobuf gem in the gemspec. AnyCable 1.6+ requires protobuf Ruby 4+, so the protobuf gem has been upgraded causing the issue.

You should either upgrade `rightway-grpc` if there is a newer version compatible with protobuf 4 or downgrade AnyCable for now.
